### ISSUE TITLE
Vercel domain bug and documentation update

### ISSUE THREAD

**Issue by xdaluca** [windingtree/developer-portal#8]
- [ ] tell Vercel there is a bug that when you point to @windingtree in cloudfare, if you have an account with them it doesn not differentiate 
- [ ] update the documentation and make this documentation live again...

**Comment by valera-rozuvan** [comment]
1. We have moved away from Vercel. Now this is hosted on https://netlify.com
2. Documentation is back up at https://developers.windingtree.com/
